# Generated by Django 3.2.16 on 2022-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.CharField(blank=True, help_text='An endpoint. Will usually have the same IP address as the peer.', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='address',
            field=models.CharField(blank=True, help_text='This is the IP address of the peer.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Internet', 'Internet or VPN'), ('SMS', 'SMS')], max_length=255, null=True),
        ),
    ]
